
package co.unicauca.restaurant.client.presentation;
import javax.swing.JFileChooser;
/**
 *
 * @author HP
 */
public class GUIAddPlatoEspecialViewController extends javax.swing.JFrame {

   String ruta = null;
    public GUIAddPlatoEspecialViewController() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_IdPlato = new javax.swing.JLabel();
        lbl_NomPlato = new javax.swing.JLabel();
        lbl_DescripPlato = new javax.swing.JLabel();
        lbl_valorPlato = new javax.swing.JLabel();
        btn_AddPlato = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_IdPlato = new javax.swing.JTextField();
        txt_NomPlato = new javax.swing.JTextField();
        txt_DescripPlato = new javax.swing.JTextField();
        txt_valorPlato = new javax.swing.JTextField();
        lbl_ImagenPlato = new javax.swing.JLabel();
        btn_ImagenPlato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Plato Especial");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 10, 210, 22);

        lbl_IdPlato.setText("Id");
        jPanel1.add(lbl_IdPlato);
        lbl_IdPlato.setBounds(20, 60, 40, 20);

        lbl_NomPlato.setText("Nombre");
        jPanel1.add(lbl_NomPlato);
        lbl_NomPlato.setBounds(20, 90, 50, 20);

        lbl_DescripPlato.setText("Descripcion");
        jPanel1.add(lbl_DescripPlato);
        lbl_DescripPlato.setBounds(20, 130, 60, 14);

        lbl_valorPlato.setText("Valor");
        jPanel1.add(lbl_valorPlato);
        lbl_valorPlato.setBounds(20, 200, 40, 20);

        btn_AddPlato.setText("Agregar Plato");
        btn_AddPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddPlatoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_AddPlato);
        btn_AddPlato.setBounds(90, 240, 100, 23);

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 240, 53, 23);
        jPanel1.add(txt_IdPlato);
        txt_IdPlato.setBounds(90, 60, 80, 20);

        txt_NomPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomPlatoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_NomPlato);
        txt_NomPlato.setBounds(90, 90, 80, 20);
        jPanel1.add(txt_DescripPlato);
        txt_DescripPlato.setBounds(90, 120, 130, 70);
        jPanel1.add(txt_valorPlato);
        txt_valorPlato.setBounds(90, 200, 80, 20);

        lbl_ImagenPlato.setBackground(new java.awt.Color(0, 0, 0));
        lbl_ImagenPlato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbl_ImagenPlato);
        lbl_ImagenPlato.setBounds(300, 60, 150, 110);

        btn_ImagenPlato.setText("Elegir Imagen");
        btn_ImagenPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImagenPlatoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ImagenPlato);
        btn_ImagenPlato.setBounds(330, 180, 100, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: Boton salir
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_NomPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomPlatoActionPerformed

    private void btn_AddPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AddPlatoActionPerformed

    private void btn_ImagenPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImagenPlatoActionPerformed
        // TODO add your handling code here:
        JFileChooser j = new JFileChooser();
        int ap= j.showOpenDialog(this);
        if(ap == JFileChooser.APPROVE_OPTION){
            ruta=j.getSelectedFile().getAbsolutePath();
            lbl_ImagenPlato.setIcon(new ImageIcon(ruta));
        }
    }//GEN-LAST:event_btn_ImagenPlatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAddPlatoEspecialViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAddPlatoEspecialViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAddPlatoEspecialViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAddPlatoEspecialViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAddPlatoEspecialViewController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddPlato;
    private javax.swing.JButton btn_ImagenPlato;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_DescripPlato;
    private javax.swing.JLabel lbl_IdPlato;
    private javax.swing.JLabel lbl_ImagenPlato;
    private javax.swing.JLabel lbl_NomPlato;
    private javax.swing.JLabel lbl_valorPlato;
    private javax.swing.JTextField txt_DescripPlato;
    private javax.swing.JTextField txt_IdPlato;
    private javax.swing.JTextField txt_NomPlato;
    private javax.swing.JTextField txt_valorPlato;
    // End of variables declaration//GEN-END:variables
}
